### ISSUE TITLE
Check if autotune and benchmarks directories are present

### ISSUE THREAD

**Issue by ShishirH** [kruize/autotune-demo#15]
When the folders autotune or benchmarks exist in the autotune-demo folder, mostly as a result of an earlier run, the minikube-demo-setup.sh throws up an error

```
#######################################
#        Autotune Demo Setup          #
#######################################


#######################################
1. Cloning autotune git repos
ERROR: git clone git@github.com:kruize/autotune.git failed.
```

To make it work as expected, we have to manually delete the folders using `rm -rf autotune benchmarks`.

Ideally, we should be either checking if the folders exist first, and then pull the changes, or just delete the folders everytime when we run the script.

**Comment by dinogun** [comment]
PR #22  fixed this issue
